### PR TITLE
WIP: Support GKE and OpenID Authentication

### LINKED ISSUE #184: GKE authentication support
This example fails for me when using a GKE cluster, but works fine for minikube:

```js
const cfg = Api.config.fromKubeconfig();
const core = new Api.Core(cfg);
core.ns.rc('http-rc').get(print);

...
{ Error: Unauthorized
    at /Users/sean/workspace/go/src/github.com/srossross/GitBotHub/githubapp/node_modules/kubernetes-client/lib/base.js:11:21
    at Request.request [as _callback] (/Users/sean/workspace/go/src/github.com/srossross/GitBotHub/githubapp/node_modules/kubernetes-client/lib/request.js:65:7)
    at Request.self.callback (/Users/sean/workspace/go/src/github.com/srossross/GitBotHub/githubapp/node_modules/request/request.js:186:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/Users/sean/workspace/go/src/github.com/srossross/GitBotHub/githubapp/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/Users/sean/workspace/go/src/github.com/srossross/GitBotHub/githubapp/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12) code: 401 }

```

Are there instructions on how to authenticate with a GKE cluster?

### PR DESCRIPTION
**Pull request by jaredallard**
### Checklist 

* [x] GKE (initial 30 min implementation, need to refine)
* [x] OpenID
* [x] ~Saves new token to kube config(?)~
* [x] Builds Successfully... 😬 
* [x] Has tests

### What does it do?

Implements a semi-standardized way of implementing `auth-providers` and refreshes authentication on-demand (i.e 401)

Fixes #184.

### CODE REVIEW

**Comment by jaredallard** [comment]
@silasbw or whoever else, for OpenID support we're going to have to have this be async, what way would you like that to proceed? `.fromKubeConfig` could become async.

**Comment by jaredallard** [comment]
OpenID support is implemented but... is async... :skull: :skull: :skull:

Need to refactor this a bit as well.

**Comment by jaredallard** [comment]
Oooooh that's a much better idea, I'll migrate it over to that.

**Comment by silasbw** [comment]
Cool.  you probably figured it out, but i'd suggesting trying to add that logic in here:

https://github.com/godaddy/kubernetes-client/blob/master/lib/request.js

File: lib/auth-providers/cmd.js [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+
+      const output = spawnSync(cmd, args, {
+        windowsHide: true
+      });
+
+      let result;
+      try {
+        result = JSON.parse(output.stdout.toString('utf8'));
+      } catch (err) {
+        return reject('Failed to run cmd.');
```
Comment (gergelyke) [inline lib/auth-providers/cmd.js]: can we `reject` with an `Error` instance instead of the `string`?

File: lib/auth-providers/cmd.js [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+
+'use strict';
+
+// for API compatability
+/* eslint no-sync: 0 */
+const spawnSync = require('child_process').spawnSync;
+
+module.exports = {
+  refresh: function (config) {
+    return new Promise((resolv, reject) => {
```
Comment (gergelyke) [inline lib/auth-providers/cmd.js]: is there any reason why it is not `resolve` but `resolve`?

File: lib/auth-providers/openid.js [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+ */
+
+const Issuer = require('openid-client').Issuer;
+
+'use strict';
+
+module.exports = {
+  refresh: function (config) {
+    return new Promise((resolv, reject) => {
+      Issuer.discover(config['idp-issuer-url']) // => Promise
```
Comment (gergelyke) [inline lib/auth-providers/openid.js]: do we need that `Promise` comment?

File: lib/config.js [hunk 4]
```diff
@@ -46,73 +63,137 @@ function getInCluster() {
...
 
+function refreshAuth(type, config) {
+  return new Promise((resolv, reject) => {
+    const provider = require(`./auth-providers/${type}.js`);
+    provider.refresh(config)
+      .then(result => {
+        let auth;
+        if (config['token-key']) {
+          const token = getProperty(config['token-key'].replace(/[{}]+/g, ''), result);
+          auth    = {
```
Comment (gergelyke) [inline lib/config.js]: can we remove the whitespaces?

File: lib/config.js [hunk 5]
```diff
@@ -46,73 +63,137 @@ function getInCluster() {
...
+      } else if (user['client-key-data']) {
+        key = Buffer.from(user['client-key-data'], 'base64').toString();
+      }
+
+      if (user.token) {
+        auth.bearer = user.token;
+      }
+
+      const authProvider = user['auth-provider'];
+      if (authProvider) {
```
Comment (gergelyke) [inline lib/config.js]: would it make sense to split this huge function into smaller ones?

File: lib/auth-providers/openid.js (hunk 3 above)
Comment (jaredallard) [reply lib/auth-providers/openid.js]: Yeah it needs to be refactored, wrote this very quickly and it's going to be transformed into on-demand refresh in `request.js`. Thanks for the review!

File: lib/auth-providers/cmd.js (hunk 1 above)
Comment (jaredallard) [reply lib/auth-providers/cmd.js]: Oops, yeah will do.

**Comment by jaredallard** [comment]
@silasbw This is ready, LMK what changes are needed, otherwise LGTM! :shipit: :tada:

File: lib/auth-providers/cmd.js (hunk 2 above)
Comment (jaredallard) [reply lib/auth-providers/cmd.js]: I've always been used to that style... then again haven't used non `async/await` in a longggg time. If this is really necessary I'll change it.

File: lib/config.js [hunk 6]
```diff
@@ -97,8 +98,33 @@ function fromKubeconfig(kubeconfig, current) {
...
 
-    if (user['auth-provider'] && user['auth-provider'].config && user['auth-provider'].config['access-token']) {
-      auth.bearer = user['auth-provider'].config['access-token'];
+    if (user['auth-provider']) {
+      const config = user['auth-provider'].config;
+
+      // if we can't determine the type, just fail later (or don't refresh).
+      let type  = null;
+      let token = null;
+      if (config['cmd-path']) {
```
Comment (silasbw) [inline lib/config.js]: Would this and https://github.com/godaddy/kubernetes-client/pull/247/files#diff-f7bf2b665273dfa66ffa4ad7c0a52bb9R111 ever both be true?  if not, can you make that clear using `else if` below?

File: lib/request.js [hunk 7]
```diff
@@ -60,9 +88,20 @@ class Request {
...
     return request(requestOptions, (err, res, body) => {
       if (err) return cb(err);
-      cb(null, { statusCode: res.statusCode, body: body });
+
+      // Refresh auth if 401
+      if (res.statusCode === 401 && auth.type) {
+        return refreshAuth(auth.type, auth.config)
+          .then(newAuth => {
+            this.requestOptions.auth = newAuth;
+            return this.request(method, options, cb);
```
Comment (silasbw) [inline lib/request.js]: Can we call `request` directly (instead of the recursive call)?  I worry about the case where the HTTP request keeps 401ing for some reason, and we end up in an infinite request loop / oom situation.

File: lib/auth-providers/openid.js [hunk 8]
```diff
@@ -0,0 +1,29 @@
...
+            client_id: config['client-id'],
+            client_secret: config['client-secret']
+          });
+
+          return client.refresh(config['refresh-token']);
+        })
+        .then(tokenSet => {
+          return resolv(tokenSet.id_token);
+        })
+        .catch(err => {
```
Comment (silasbw) [inline lib/auth-providers/openid.js]: nit: `.catch(reject);`

**Comment by silasbw** [comment]
Thanks again @jaredallard :hot_pepper: :hot_pepper: :hot_pepper: !

**Comment by jaredallard** [comment]
🎉🎉🎉 What's the timeline for this being pushed to npm?

**Comment by silasbw** [comment]
We'll do it today and post an update on https://github.com/godaddy/kubernetes-client/issues/184 afterwards.
